[package]
name = "mev-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0.14", features = ["abigen", "ws", "ethers-solc"] }
serde_json = "1.0.133"
tokio = { version = "1.29.0", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
