[package]
name = "mev-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
envconfig = "0.11.0"
tokio = {version =  "1.43.0", features = ["full"]}
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"
alloy = {version ="0.9.2", features = ["full"]}
futures-util = "0.3"