[workspace.package]
version = "1.7.1"
authors = ["Kuzmin Dmitry"]
edition = "2021"
license = "GPL-3.0"
rust-version = "1.84"

[workspace]
members = ["bot", "strategies"]

[workspace.dependencies]
envconfig = "0.11.0"
tokio = { version = "1.43.0", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"
alloy = { version = "0.9.2", features = [
    "full",
    "provider-anvil-api",
    "rpc-client-ipc",
] }
futures-util = "0.3"
serde_json = "1.0.137"
serde = "1.0.217"
hex = "0.4.3"
tracing-appender = "0.2.3"
anyhow = "1.0.95"
enum-iterator = "2.1.0"

# local deps
bot = { path = "bot" }
strategies = { path = "strategies" }
