[package]
name = "mev-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0.14", features = ["abigen", "ws", "ethers-solc"] }
serde_json = "1.0.133"
tokio = { version = "1.29.0", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
log = "0.4.17"
fern = { version = "0.7.0", features = ["colored"]}
colored = { version = "2.1.0", default-features = false }
anyhow = "1.0.93"
chrono = "0.4.38"
serde = "1.0.215"
envconfig = "0.11.0"
hex = "0.4.3"
